const timelineDataDay1 = [
	{
	  id: 1,
	  title: "Innovate-X, Slot-I",
	  time: "09:00 AM",
	  location: "Seminar Room, Dept. of Industrial & Systems Engg.",
	  link: "https://maps.app.goo.gl/USTHoae3Dnx4t4Nj9",
	  image: "src/assets/Timeline/Innovate-X.png",
	  position: "left",
	},
	{
	  id: 2,
	  title: "Fine-Tuning MIP Solvers for Improved Performance, Workshop",
	  time: "10:00 AM",
	  location: "NR-311, Nalanda Classroom Complex",
	  link: "https://maps.app.goo.gl/4E9RiAob3fenRGjj9",
	  image: "src/assets/Timeline/DecisionOpt-WS.png",
	  position: "right",
	},
	{
	  id: 3,
	  title: "CodeOps",
	  time: "11:30 AM",
	  location: "ORDS Lab, Dept. of Industrial & Systems Engg.",
	  link: "https://maps.app.goo.gl/USTHoae3Dnx4t4Nj9",
	  image: "src/assets/Timeline/CodeOps.png",
	  position: "left",
	},
	{
	  id: 4,
	  title: "IBM, Guest Lecture",
	  time: "12:00 PM",
	  location: "Raman Auditorium",
	  link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
	  image: null,
	  position: "right",
	},
	{
	  id: 5,
	  title: "Innovate-X, Slot-II",
	  time: "01:30 PM",
	  location: "Seminar Room, Dept. of Industrial & Systems Engg.",
	  link: "https://maps.app.goo.gl/USTHoae3Dnx4t4Nj9",
	  image: null,
	  position: "left",
	},
	{
	  id: 6,
	  title: "Stratathon",
	  time: "02:00 PM",
	  location: "NR-311, Nalanda Classroom Complex",
	  link: "https://maps.app.goo.gl/4E9RiAob3fenRGjj9",
	  image: null,
	  position: "right",
	},
	{
	  id: 7,
	  title: "Dr. Anindita Desarkar",
	  time: "02:00 PM",
	  location: "Raman Auditorium",
	  link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
	  image: null,
	  position: "left",
	},
	{
	  id: 8,
	  title: "Datavantage Round-I",
	  time: "02:30 PM",
	  location: "E1, Department of Industrial & Systems Engineering",
	  link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
	  image: null,
	  position: "right",
	},
	{
	  id: 9,
	  title: "Nitish Kumar, Guest Lecture",
	  time: "04:30 PM",
	  location: "Raman Auditorium",
	  link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
	  image: null,
	  position: "left",
	},
	{
	  id: 10,
	  title: "Operheimer, Slot-I",
	  time: "05:30 PM",
	  location: "Seminar Room, Dept. of Industrial and Systems Engg.",
	  link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
	  image: null,
	  position: "right",
	},
	{
	  id: 11,
	  title: "Tech-Powered Growth-Innovations Driving Business Success, Workshop",
	  time: "06:00 PM",
	  location: "Raman Auditorium",
	  link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
	  image: null,
	  position: "left",
	},
	{
	  id: 12,
	  title: "Women's Panel",
	  time: "08:00 PM",
	  location: "Raman Auditorium",
	  link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
	  image: null,
	  position: "right",
	},
  ];
  
  export default timelineDataDay1;
  