const timelineDataDay1 = [
  {
    id: 1,
    title: "Innovate-X Slot-I",
    time: "09:00 AM",
    location: "Seminar Room, Dept. of Industrial & Systems Engg.",
    link: "https://maps.app.goo.gl/USTHoae3Dnx4t4Nj9",
    image: "src/assets/Timeline/Innovate-X.png",
    position: "left",
  },
  {
    id: 2,
    title: "Fine Tuning MIP Solvers Workshop by DecisionOpt",
    time: "10:00 AM",
    location: "NR-311, Nalanda Classroom Complex",
    link: "https://maps.app.goo.gl/4E9RiAob3fenRGjj9",
    image: "src/assets/Timeline/DecisionOpt-WS.png",
    position: "right",
  },
  {
    id: 3,
    title: "CodeOps",
    time: "11:30 AM",
    location: "ORDS Lab, Dept. of Industrial & Systems Engg.",
    link: "https://maps.app.goo.gl/USTHoae3Dnx4t4Nj9",
    image: "src/assets/Timeline/CodeOps.png",
    position: "left",
  },
  {
    id: 4,
    title: "Strategy Sutram",
    time: "11:30 AM",
    location: "C3, Dept. of Industrial & Systems Engg.",
    link: "https://maps.app.goo.gl/USTHoae3Dnx4t4Nj9",
    image: "src/assets/Timeline/Strategy_Sutram.png",
    position: "right",
  },
  {
    id: 5,
    title: "IBM, Guest Lecture",
    time: "12:00 PM",
    location: "Raman Auditorium",
    link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
    image: null,
    position: "left",
  },
  {
    id: 6,
    title: "Innovate-X Slot-II",
    time: "02:00 PM",
    location: "Seminar Room, Dept. of Industrial & Systems Engg.",
    link: "https://maps.app.goo.gl/USTHoae3Dnx4t4Nj9",
    image: "src/assets/Timeline/Innovate-X.png",
    position: "right",
  },
  {
    id: 7,
    title: "Stratathon",
    time: "02:00 PM",
    location: "NR-311, Nalanda Classroom Complex",
    link: "https://maps.app.goo.gl/4E9RiAob3fenRGjj9",
    image: "src/assets/Timeline/Stratathon.png",
    position: "left",
  },
  {
    id: 8,
    title: "Dr. Anindita Desarkar, Guest Lecture",
    time: "02:00 PM",
    location: "Raman Auditorium",
    link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
    image: "src/assets/Timeline/Anindita.png",
    position: "right",
  },
  {
    id: 9,
    title: "Datavantage Round-I",
    time: "02:30 PM",
    location: "E1, Department of Industrial & Systems Engineering",
    link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
    image: "src/assets/Timeline/Datavantage.png",
    position: "left",
  },
  {
    id: 10,
    title: "Nitish Kumar, Guest Lecture",
    time: "04:00 PM",
    location: "Raman Auditorium",
    link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
    image: "src/assets/GuestLectures/Nitish_kumar.webp",
    position: "right",
  },
  {
    id: 11,
    title: "Operheimer Slot-I",
    time: "05:30 PM",
    location: "Seminar Room, Dept. of Industrial and Systems Engg.",
    link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
    image: "src/assets/Timeline/Operheimer.png",
    position: "left",
  },
  {
    id: 12,
    title: "Tech-Powered Growth Workshop by Hire3x",
    time: "06:00 PM",
    location: "Raman Auditorium",
    link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
    image: "src/assets/Timeline/Hire3x.png",
    position: "right",
  },
  {
    id: 13,
    title: "Women's Panel",
    time: "08:00 PM",
    location: "Raman Auditorium",
    link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
    image: null,
    position: "left",
  },
];

export default timelineDataDay1;
