import img1 from "../assets/GuestLectures/Rajesh-Kumar.jpg";
import img2 from "../assets/GuestLectures/Arvind-Kumar.jpeg";
import img3 from "../assets/GuestLectures/Nitish_kumar.jpg";
import img4 from "../assets/GuestLectures/Anindita_Desarkar.jpg";
import img5 from "../assets/GuestLectures/Diptiman_Dasgupta.png";
import img6 from "../assets/GuestLectures/Suman_Das.png";
import img7 from "../assets/GuestLectures/Saptaswa_Sarkar.png";


export const guestLectures = [
  {
    id: "0",
    imgUrl: img1,
    name: "Dr. Rajesh Kumar",
    designation: "Director, Business Analytics",
    company: "Philips",
    topic: "Driving Supply Chain digital transformation through data Analytics",
    desc: "Dr. Rajesh Kumar is the Director of Business Analytics at Philips integrated supply chain digital center of excellence. He has 20+ years of experience spanning across organizations like SCG Chemicals, DXC Technologies, HP, i2 Technologies, EY and Volvo-Eicher. He holds a degree in mechanical engineering from NIT Bhopal and a masters and PhD from Indian Institute of Science Bangalore.",
    linkedin: "https://www.linkedin.com/in/dr-rajesh-kumar-0b86a38/",
    companyUrl: "https://www.philips.co.in/",
    path: "/Rajesh-Kumar",
    onlineMeetLink: "https://teams.microsoft.com/l/message/19:fbdChIuFG8N2khxBz_jJ3VfHyHexNBZe_Wnan9hmc2M1@thread.tacv2/1740659840142?tenantId=71dbb522-5704-4537-9f25-6ad2dcd4278d&groupId=77bb36ab-8845-492b-b417-976cf0b53a24&parentMessageId=1740659840142&teamName=Optima%202025%20%7C%20IIT%20Kharagpur&channelName=General&createdTime=1740659840142",
    date: "Date: 1st March",
    mode: "Mode: Online",
  },
  {
    id: "1",
    imgUrl: img2,
    name: "Dr. Arvind Kumar",
    designation: "Senior Advisor",
    company: "Optym",
    topic: "Analytics for Electric Vehicles (EVs) and Related Domains",
    desc: "Dr. Arvind Kumar is a seasoned Operations Research practitioner with over 20 years of experience in enabling large logistics, transportation and e-mobility companies to leverage power of analytics for better planning and execution. Besides his previous leadership role of VP - Research and Development at Optym, he has also advised several startups and small businesses in converting business problems to mathematical formulation, and mature the process of applying OR tools to solve these problems in real-life environment. He holds a BTech in Chemical Engg from IIT Chennai, and a PhD in Industrial & Systems Engg from University of Florida. He is also recipient of best paper awards in the field of medical and military applications at INFORMS.",
    linkedin: "https://www.linkedin.com/in/arviphd/",
    companyUrl: "https://www.optym.com/",
    path: "/Arvind-Kumar",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "2",
    imgUrl: img3,
    name: "Nitish Kumar",
    designation: "Head Analyst",
    company: "Tata Steel",
    topic: "Predictive modelling",
    desc: "Nitish Kumar is the Head Analyst for Manufacturing at Tata Steel, with over 11 years of experience in data science, machine learning, and predictive analytics. He holds a Bachelor of Engineering degree in Computer Science from BIT Mesra (2013). He began his career at Tata Steel in 2013 as a Management Trainee and contributed to the IT team from 2016 to 2018. Following a company-sponsored training program in Data Science, he transitioned to the Data Analytics Team in 2018. His professional interests lie in data science and optimization modeling, and he has a proven track record of developing and implementing data-driven solutions across various business areas, including raw materials, iron making, procurement, and supply chain. Notable achievements in his career include leading a cross-functional team for the Integrated Margin Management project, which spans multiple value chains such as coal, metallics, flux, and ferro alloys. He has also developed price prediction models for key commodities like coal, zinc, and Ferroshot, created plant digital twins to optimize operations, and completed over 50 EBITDA projects utilizing data analytics models across different locations. Additionally, he has filed four patents in the last three years. Beyond his professional endeavors, he is passionate about chess, podcasts, and travel.",
    linkedin: "https://www.linkedin.com/in/nitish-kumar-446b4258/",
    companyUrl: "https://www.tatasteel.com/",
    path: "/Nitish-Kumar",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "3",
    imgUrl: img4,
    name: "Dr. Anindita Desarkar",
    designation: "Director",
    company: "LTIMindtree",
    topic: "Revolutionizing Optimization using Generative AI",
    desc: "Dr. Anindita Desarkar (Director - LTIMindtree), An IT Professional having 20 years' experience, working predominantly on Analytics and Machine Learning domain; expert areas include Generative AI, NLP, Predictive Maintenance and AI based Optimization. A dedicated researcher, PhD on “Machine Learning & Analytics” from Jadavpur University having 22+ publications in various SCOPUS indexed journals and conferences. Filed 5 patents in Optimization and AI domain.",
    linkedin: "https://www.linkedin.com/in/anindita-desarkar-phd-b9a127218?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    companyUrl: "https://www.ltimindtree.com/",
    path: "/Anindita-Desarkar",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "4",
    imgUrl: img5,
    name: "Diptiman Dasgupta",
    designation: "Associate Director & Executive IT Architect",
    company: "IBM",
    topic: null,
    desc: "Diptiman Dasgupta (DD) is an IBM Associate Director & Executive IT Architect with 28+ years of Industry & Research experiences in diverse field of IT in different IT giants like IBM, Cognizant, PwC etc. Last 22 years he is with IBM and played a pivotal role in driving new tech areas & complex projects in the area of Blockchain, Sustainability, Cloud etc. He has spent most of his career in Architecture track and was Architect Profession Leader in IBM for quite long time. He has done his B.E in Electrical Engg. & ME in Computer Sc. & Information Tech and he has multiple publications in many international journals of repute as well as many patents to his credit.",
    linkedin: "https://www.linkedin.com/in/diptimandasgupta/",
    path: "/Diptiman-Dasgupta",
    companyUrl: null,
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "5",
    imgUrl: img6,
    name: "Suman Das",
    designation: "Digital Transformation Leader",
    company: "IBM",
    topic: null,
    desc: "An IIM Calcutta & XLRI (Jamshedpur) Alumni, Suman Das is a Digital Transformation Leader in IBM with around 24 years of Industry experience. He specializes in Delivery Management, Strategy Consulting, Product development, Method Development, AI Governance, Customer Relationship management and in technology domains of  Blockchain & Hybrid Cloud. A patent holder, he has multiple awards, certifications & journal publications to his credit. He enjoys mentoring & teaching and has taken numerous technology and management sessions across many universities, industry bodies and institutes like PMI, IIT & IIM as part of Industry-Academia partnership. He is also a certified Independent Director from Indian Institute of Corporate Affairs (Under the Aegis of Ministry of Corporate Affairs, Govt. of India) & certified in ESG (Environment, Sustainability and Governance).",
    linkedin: "https://www.linkedin.com/in/suman-das-841b4532/",
    path: "/Suman-Das",
    companyUrl: null,
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "6",
    imgUrl: img7,
    name: "Saptaswa Sarkar",
    designation: "Product Manager & Senior Architect",
    company: "Airasia",
    topic: null,
    desc: "Saptaswa Sarkar is currently with Airasia Barhad as Product Manager and Senior Solution Architect. He is having 20 + years of experience in IT industry in various roles, specifically in Technology areas. He worked in multiple domains like Travel and Transport Industry, Telecom, Life Science, Airlines Industry etc. in variety of technologies and frameworks including as latest as Blockchain. During this many years of journey, he was primarily engaged in Software Designing, Development, Testing, Automation etc. and also in architecting solution for new application as per Client's requirements. He is avid photographer and loves cooking and singing.",
    linkedin: "https://www.linkedin.com/in/saptaswasarkar/",
    path: "/Saptaswa-Sarkar",
    companyUrl: "https://www.airasia.com/en/gb",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
];
