import img1 from "../assets/GuestLectures/Rajesh-Kumar.webp";
import img2 from "../assets/GuestLectures/Arvind-Kumar.webp";
import img3 from "../assets/GuestLectures/Nitish_kumar.webp";
import img4 from "../assets/GuestLectures/Anindita_Desarkar.webp";
import img5 from "../assets/GuestLectures/Diptiman_Dasgupta.webp";
import img6 from "../assets/GuestLectures/Suman_Das.webp";
import img7 from "../assets/GuestLectures/Saptaswa_Sarkar.webp";
import img8 from "../assets/GuestLectures/Pallavi-Gupta-Bhowmick.webp";
import img9 from "../assets/GuestLectures/Papli-Banerjee.webp";
import img10 from "../assets/GuestLectures/Deepa-Duraisamy.webp";

export const guests=[
  {
    title:"Chief Guest",
    img:"src/assets/GuestLectures/sk_nayak.png",
    name:"Shri S K Nayak",
    designation:"Director of PXE Lab, DRDO",
    linkedin:"https://www.drdo.gov.in/drdo/labs-and-establishments/proof-experimental-establishment-pxe"
  },
  {
    title:"Guest of Honor",
    img:"src/assets/GuestLectures/Sanjoy_Chatterjee.jpeg",
    name:"Shri Sanjoy Chatterjee",
    designation:"Chair of NASSCOM, Regional Council-East",
    linkedin:"https://www.linkedin.com/in/sanjoynet/"
  }
]
export const guestLectures = [
  // {
  //   id: "0",
  //   imgUrl: img1,
  //   name: "Shri S K Nayak (Chief Guest)",
  //   designation: "Director of PXE Lab, DRDO",
  //   company: null,
  //   topic: null,
  //   desc: "",
  //   linkedin: "",
  //   companyUrl: null,
  //   path: "/Rajesh-Kumar",
  //   onlineMeetLink: null,
  //   date: "04:30pm | 7th March, Opening Ceremony",
  //   mode: "Netaji Auditorium",
  // },
  // {
  //   id: "1",
  //   imgUrl: "src/assets/GuestLectures/Sanjoy_Chatterjee.jpeg",
  //   name: "Shri Sanjoy Chatterjee (Guest of Honor)",
  //   designation: "Chair of NASSCOM, Regional Council-East",
  //   company: null,
  //   topic: null,
  //   desc: "",
  //   linkedin: "https://www.linkedin.com/in/sanjoynet/",
  //   companyUrl: null,
  //   path: "/Rajesh-Kumar",
  //   onlineMeetLink: null,
  //   date: "04:30pm | 7th March, Opening Ceremony",
  //   mode: "Netaji Auditorium",
  // },
  {
    id: "2",
    imgUrl: img1,
    name: "Dr. Rajesh Kumar",
    designation: "Director, Business Analytics",
    company: "Philips",
    topic: "Driving Supply Chain digital transformation through data Analytics",
    desc: "Dr. Rajesh Kumar is the Director of Business Analytics at Philips integrated supply chain digital center of excellence. He has 20+ years of experience spanning across organizations like SCG Chemicals, DXC Technologies, HP, i2 Technologies, EY and Volvo-Eicher. He holds a degree in mechanical engineering from NIT Bhopal and a masters and PhD from Indian Institute of Science Bangalore.",
    linkedin: "https://www.linkedin.com/in/dr-rajesh-kumar-0b86a38/",
    companyUrl: "https://www.philips.co.in/",
    path: "/Rajesh-Kumar",
    onlineMeetLink: "https://teams.microsoft.com/l/message/19:fbdChIuFG8N2khxBz_jJ3VfHyHexNBZe_Wnan9hmc2M1@thread.tacv2/1740659840142?tenantId=71dbb522-5704-4537-9f25-6ad2dcd4278d&groupId=77bb36ab-8845-492b-b417-976cf0b53a24&parentMessageId=1740659840142&teamName=Optima%202025%20%7C%20IIT%20Kharagpur&channelName=General&createdTime=1740659840142",
    date: "05:00pm | 1st March",
    mode: "MS Teams(online)",
  },
  {
    id: "3",
    imgUrl: img2,
    name: "Dr. Arvind Kumar",
    designation: "Senior Advisor",
    company: "Optym",
    topic: "Analytics for Electric Vehicles (EVs) and Related Domains",
    desc: "Dr. Arvind Kumar is a seasoned Operations Research practitioner with over 20 years of experience in enabling large logistics, transportation and e-mobility companies to leverage power of analytics for better planning and execution. Besides his previous leadership role of VP - Research and Development at Optym, he has also advised several startups and small businesses in converting business problems to mathematical formulation, and mature the process of applying OR tools to solve these problems in real-life environment. He holds a BTech in Chemical Engg from IIT Chennai, and a PhD in Industrial & Systems Engg from University of Florida. He is also recipient of best paper awards in the field of medical and military applications at INFORMS.",
    linkedin: "https://www.linkedin.com/in/arviphd/",
    companyUrl: "https://www.optym.com/",
    path: "/Arvind-Kumar",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "4",
    imgUrl: img3,
    name: "Nitish Kumar",
    designation: "Head Analyst",
    company: "Tata Steel",
    topic: "AI Journey of Tata Steel",
    desc: "Nitish Kumar is the Head Analyst for Manufacturing at Tata Steel, with over 11 years of experience in data science, machine learning, and predictive analytics. He holds a Bachelor of Engineering degree in Computer Science from BIT Mesra (2013). He began his career at Tata Steel in 2013 as a Management Trainee and contributed to the IT team from 2016 to 2018. Following a company-sponsored training program in Data Science, he transitioned to the Data Analytics Team in 2018. His professional interests lie in data science and optimization modeling, and he has a proven track record of developing and implementing data-driven solutions across various business areas, including raw materials, iron making, procurement, and supply chain. Notable achievements in his career include leading a cross-functional team for the Integrated Margin Management project, which spans multiple value chains such as coal, metallics, flux, and ferro alloys. He has also developed price prediction models for key commodities like coal, zinc, and Ferroshot, created plant digital twins to optimize operations, and completed over 50 EBITDA projects utilizing data analytics models across different locations. Additionally, he has filed four patents in the last three years. Beyond his professional endeavors, he is passionate about chess, podcasts, and travel.",
    linkedin: "https://www.linkedin.com/in/nitish-kumar-b384b3169?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    companyUrl: "https://www.tatasteel.com/",
    path: "/Nitish-Kumar",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "5",
    imgUrl: img4,
    name: "Dr. Anindita Desarkar",
    designation: "Director",
    company: "LTIMindtree",
    topic: "Revolutionizing Optimization using Generative AI",
    desc: "Dr. Anindita Desarkar (Director - LTIMindtree), An IT Professional having 20 years' experience, working predominantly on Analytics and Machine Learning domain; expert areas include Generative AI, NLP, Predictive Maintenance and AI based Optimization. A dedicated researcher, PhD on “Machine Learning & Analytics” from Jadavpur University having 22+ publications in various SCOPUS indexed journals and conferences. Filed 5 patents in Optimization and AI domain.",
    linkedin: "https://www.linkedin.com/in/anindita-desarkar-phd-b9a127218?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    companyUrl: "https://www.ltimindtree.com/",
    path: "/Anindita-Desarkar",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "6",
    imgUrl: img5,
    name: "Diptiman Dasgupta",
    designation: "Associate Director & Executive IT Architect",
    company: "IBM",
    topic: null,
    desc: "Diptiman Dasgupta (DD) is an IBM Associate Director & Executive IT Architect with 28+ years of Industry & Research experiences in diverse field of IT in different IT giants like IBM, Cognizant, PwC etc. Last 22 years he is with IBM and played a pivotal role in driving new tech areas & complex projects in the area of Blockchain, Sustainability, Cloud etc. He has spent most of his career in Architecture track and was Architect Profession Leader in IBM for quite long time. He has done his B.E in Electrical Engg. & ME in Computer Sc. & Information Tech and he has multiple publications in many international journals of repute as well as many patents to his credit.",
    linkedin: "https://www.linkedin.com/in/diptimandasgupta/",
    path: "/Diptiman-Dasgupta",
    companyUrl: null,
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "7",
    imgUrl: img6,
    name: "Suman Das",
    designation: "Digital Transformation Leader",
    company: "IBM",
    topic: null,
    desc: "An IIM Calcutta & XLRI (Jamshedpur) Alumni, Suman Das is a Digital Transformation Leader in IBM with around 24 years of Industry experience. He specializes in Delivery Management, Strategy Consulting, Product development, Method Development, AI Governance, Customer Relationship management and in technology domains of  Blockchain & Hybrid Cloud. A patent holder, he has multiple awards, certifications & journal publications to his credit. He enjoys mentoring & teaching and has taken numerous technology and management sessions across many universities, industry bodies and institutes like PMI, IIT & IIM as part of Industry-Academia partnership. He is also a certified Independent Director from Indian Institute of Corporate Affairs (Under the Aegis of Ministry of Corporate Affairs, Govt. of India) & certified in ESG (Environment, Sustainability and Governance).",
    linkedin: "https://www.linkedin.com/in/suman-das-841b4532/",
    path: "/Suman-Das",
    companyUrl: null,
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "8",
    imgUrl: img7,
    name: "Saptaswa Sarkar",
    designation: "Product Manager & Senior Architect",
    company: "AirAsia",
    topic: null,
    desc: "Saptaswa Sarkar is currently with Airasia Barhad as Product Manager and Senior Solution Architect. He is having 20 + years of experience in IT industry in various roles, specifically in Technology areas. He worked in multiple domains like Travel and Transport Industry, Telecom, Life Science, Airlines Industry etc. in variety of technologies and frameworks including as latest as Blockchain. During this many years of journey, he was primarily engaged in Software Designing, Development, Testing, Automation etc. and also in architecting solution for new application as per Client's requirements. He is avid photographer and loves cooking and singing.",
    linkedin: "https://www.linkedin.com/in/saptaswasarkar/",
    path: "/Saptaswa-Sarkar",
    companyUrl: "https://www.airasia.com/en/gb",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "9",
    imgUrl: img8,
    name: "Pallavi Gupta Bhowmick",
    designation: "Managing Director",
    company: "Accenture Strategy and Consulting",
    topic: null,
    desc: "With over 20 years of experience in both services and product organizations, Pallavi has led global programs and talent across five continents. Her career includes extensive leadership roles at GE, HP, Adobe, Unilever, and Accenture, where she transitioned from practice leadership to C-level advisory. Pallavi is an expert in driving AI-powered transformations and helping organizations navigate the intersection of technology and business strategy. Passionate about building diverse, high-performing teams, she fosters innovation and delivers measurable impact. A strong advocate for Diversity, Equity, and Inclusion, Pallavi works to create workplaces where authenticity and inclusive leadership thrive.",
    linkedin: "https://www.linkedin.com/in/pallavibhowmick?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app/",
    path: "/Pallavi-Gupta",
    companyUrl: "https://www.accenture.com/us-en/about/consulting-index",
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "10",
    imgUrl: img9,
    name: "Papli Banerjee",
    designation: "Director Business Analytics & GM India office, Amplify Analytix",
    company: null,
    topic: null,
    desc: "As the Director of Business Analytics at Amplify Analytix, she leads a multi-skilled team using data science to drive strategic decisions. With over 20 years of experience in sales, marketing, and business transformation, she has built high-performing analytics teams that deliver measurable impact. Her expertise includes shaping analytics roadmaps, defining data strategies, and optimizing customer retention models. She specializes in data quality, NPS survey analysis, and stakeholder collaboration, ensuring businesses extract meaningful insights. She also works closely with product quality teams to enhance customer experience and market competitiveness. Passionate about data-driven decision-making, she empowers business leaders to unlock analytics' full potential. Outside work, she enjoys time with her teenage daughter, valuing adaptability in both life and analytics.",
    linkedin: "https://www.linkedin.com/in/papli-banerjee?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    path: "/Papli-Banerjee",
    companyUrl: null,
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "11",
    imgUrl: img10,
    name: "Deepa Duraisamy",
    designation: "Head of Data, Edelweiss Life Insurance",
    company: null,
    topic: null,
    desc: "Deepa Duraisamy is an accomplished data professional with over 2 decades of industry experience across domains of banking, insurance and FMCG. In her role as Head of Data at Edelweiss Life Insurance she, along with her team, takes on and delivers initiatives that significantly improve customer experience, enable business growth and streamline operations. She has a track record of running large delivery programs, globally executed at scale, across data management and analytics. As a change agent she believes in fostering a collaborative, tech enabled environment, managing stakeholder relationships and employee engagement.",
    linkedin: "https://www.linkedin.com/in/deepa-duraisamy/",
    path: "/Deepa-Duraisamy",
    companyUrl: null,
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
  {
    id: "12",
    imgUrl: "src/assets/GuestLectures/Tanushyam_Chattopadhyay.png",
    name: "Dr. Tanushyam Chattopadhyay",
    designation: "Practice Head Computer Vision, Sirius Digitech",
    company: null,
    topic: "Seeing the future : Innovations & Applications in Computer Vision",
    desc: "Exploring the cutting-edge advancements in computer vision, this guide delves into breakthrough technologies, AI-driven enhancements, and real-world applications transforming industries. From autonomous systems to medical imaging and smart surveillance, discover how machine perception is reshaping the future, driving automation, and revolutionizing human-computer interaction with unprecedented accuracy and efficiency.",
    linkedin: "https://www.linkedin.com/in/tanushyam-chattopadhyay-80291a11?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    path: "/Tanush-Chattopadhyay",
    companyUrl: null,
    onlineMeetLink: null,
    date: null,
    mode: null,
  },
];
